
CREATE TABLE DIM_CANAIS(
    ID_CANAL VARCHAR(40) NOT NULL PRIMARY KEY,
    NM_CANAL VARCHAR(80) NOT NULL,
    DATA_INSERCAO DATETIME DEFAULT GETDATE()

)



CREATE TABLE DIM_VIDEO(
    ID_VIDEO VARCHAR(40) NOT NULL PRIMARY KEY,
    NM_VIDEO VARCHAR(80) NOT NULL,
    DATA_INSERCAO DATETIME DEFAULT GETDATE()

)


CREATE TABLE FT_ESTATISTICA_VIDEO(
    ID_CANAL VARCHAR(40) NOT NULL,
    ID_VIDEO VARCHAR(40) NOT NULL,
    TOTAL_VISUALIZACOES INT NOT NULL,
    TOTAL_LIKES INT NOT NULL,
    TOTAL_FAVORITOS INT NOT NULL,
    TOTAL_COMENTARIOS INT NOT NULL,
    CONSTRAINT FK_ESTATISTICA_CANAL FOREIGN KEY (ID_CANAL) REFERENCES DIM_CANAIS(ID_CANAL),
    CONSTRAINT FK_ESTATISTICA_VIDEO FOREIGN KEY (ID_VIDEO) REFERENCES DIM_VIDEO(ID_VIDEO)
)

ALTER TABLE FT_ESTATISTICA_VIDEO
ADD DATA_INSERCAO  DATETIME DEFAULT GETDATE();

ALTER TABLE FT_ESTATISTICA_VIDEO
ADD DATA_ATUALIZACAO  DATETIME DEFAULT GETDATE();


SELECT *
FROM FT_ESTATISTICA_VIDEO;